version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-11  # Use the desired Maven and JDK version

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Set up environment
          command: |
            echo "export MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" >> ~/.bashrc
            source ~/.bashrc

      - run:
          name: Install dependencies
          command: mvn install -DskipTests=true -B -V


      - run:
          name: Run tests
          command: mvn test "-Dcucumber.filter.tags=@ui"

